# ---- render_tests ------------------------------------------------------
add_executable(
    render_tests
    ${CMAKE_CURRENT_SOURCE_DIR}/test_assets.qrc
    render/prop_model_footprint_test.cpp
    render/rock_prop_mesh_test.cpp
    render/tent_mesh_test.cpp
    render/gl_deferred_delete_test.cpp
    render/gl_context_lifetime_test.cpp
    render/asset_counters_test.cpp
    render/unit_primitive_convention_test.cpp
    render/instance_draw_guard_test.cpp
    render/pose_controller_test.cpp
    render/wildlife_action_pose_test.cpp
    render/wildlife_clip_selection_test.cpp
    render/sheep_rig_integrity_test.cpp
    render/wolf_rig_integrity_test.cpp
    render/pose_controller_compatibility_test.cpp
    render/mounted_pose_controller_test.cpp
    render/body_frames_test.cpp
    render/grip_axis_test.cpp
    render/equipment_registry_test.cpp
    render/equipment_loadout_catalog_test.cpp
    render/helmet_renderers_test.cpp
    render/armor_renderer_test.cpp
    render/carthage_armor_bounds_test.cpp
    render/rider_proportions_test.cpp
    render/infantry_proportions_test.cpp
    render/horse_equipment_renderers_test.cpp
    render/spawn_validator_test.cpp
    render/battle_render_optimizer_test.cpp
    render/barracks_flag_renderer_test.cpp
    render/carried_load_renderer_test.cpp
    render/building_archetype_desc_test.cpp
    render/farm_activity_test.cpp
    render/home_activity_test.cpp
    render/siege_crew_test.cpp
    render/market_awning_test.cpp
    render/building_facade_coplanarity_test.cpp
    render/building_body_footprint_test.cpp
    render/building_render_common_test.cpp
    render/static_building_batch_test.cpp
    render/static_mesh_pack_test.cpp
    render/attachment_mesh_pack_test.cpp
    render/mode_indicator_test.cpp
    render/mode_indicator_placement_test.cpp
    render/shader_source_test.cpp
    render/visibility_mask_encoder_test.cpp
    render/fog_renderer_test.cpp
    render/render_view_state_test.cpp
    render/sky_box_transition_test.cpp
    render/renderer_visibility_policy_test.cpp
    render/unit_render_cache_test.cpp
    render/frame_cadence_test.cpp
    render/render_archetype_test.cpp
    render/draw_queue_sort_order_test.cpp
    render/draw_queue_sort_cost_test.cpp
    render/effect_batch_dispatch_test.cpp
    render/spark_direction_test.cpp
    render/linear_feature_geometry_test.cpp
    render/road_network_geometry_test.cpp
    render/linear_feature_visibility_test.cpp
    render/ground_utils_test.cpp
    render/dead_tree_mesh_test.cpp
    render/prop_mesh_builder_test.cpp
    render/local_lighting_test.cpp
    render/contact_shadow_test.cpp
    render/terrain_grounding_test.cpp
    render/shadow_cascade_fit_test.cpp
    render/shader_reload_test.cpp
    render/weather_particle_budget_test.cpp
    render/graphics_lighting_settings_test.cpp
    render/scatter_composition_test.cpp
    render/scatter_gpu_retention_test.cpp
    render/scatter_runtime_test.cpp
    render/terrain_scene_proxy_test.cpp
    render/render_thread_boundary_test.cpp
    render/scene_walk_entity_handle_test.cpp
    render/map_boundary_fog_renderer_test.cpp
    render/oriented_parts_test.cpp
    render/draw_part_material_test.cpp
    render/roman_light_helmet_mesh_test.cpp
    render/rig_dsl_interpreter_test.cpp
    render/rigged_pipeline_test.cpp
    render/pipeline/lod_selector_test.cpp
    render/pipeline/screen_metrics_test.cpp
    render/pipeline/creature_lod_decision_test.cpp
    render/pipeline/creature_asset_registry_test.cpp
    render/pipeline/instance_coalescer_test.cpp
    render/pass/frame_pass_runner_test.cpp
    render/rig_dsl/barracks_rig_test.cpp
    render/bpat/bpat_format_test.cpp
    render/bpat/asset_compression_test.cpp
    render/bpat/bpat_registry_test.cpp
    render/formation_locomotion_state_test.cpp
    render/humanoid/skeleton_test.cpp
    render/humanoid/humanoid_spec_test.cpp
    render/horse/mounted_seat_frame_test.cpp
    render/horse/mounted_rider_seat_test.cpp
    render/horse/horse_spec_test.cpp
    render/horse/horse_anatomy_test.cpp
    render/elephant/elephant_spec_test.cpp
    render/elephant/elephant_source_asset_test.cpp
    render/stateless_weapon_renderers_test.cpp
    render/creature/skeleton_test.cpp
    render/creature/species_manifest_parity_test.cpp
    render/creature/commander_leg_pose_test.cpp
    render/creature/part_graph_test.cpp
    render/creature/creature_visual_definition_test.cpp
    render/creature/rigged_mesh_bake_test.cpp
    render/creature/rigged_mesh_cache_test.cpp
    render/creature/static_attachment_bake_test.cpp
    render/creature/quadruped_topology_test.cpp
    render/creature/quadruped_gait_test.cpp
    render/creature/combat_visual_state_test.cpp
    render/creature/transition_continuity_test.cpp
    render/creature/combat_root_motion_test.cpp
    render/creature/soldier_turn_smoothing_test.cpp
    render/creature/humanoid_prepare_test.cpp
    render/creature/humanoid_golden_parity_test.cpp
    render/creature/humanoid_asset_key_test.cpp
    render/creature/humanoid_asset_prewarm_test.cpp
    render/creature/quadruped_golden_parity_test.cpp
    render/creature/quadruped_asset_key_test.cpp
    render/creature/death_collapse_test.cpp
    render/creature/horse_prepare_test.cpp
    render/creature/elephant_prepare_test.cpp
    render/creature/quadruped_clip_set_test.cpp
    render/creature/quadruped_mesh_graph_test.cpp
    render/creature/mounted_prepare_test.cpp
    render/creature/creature_render_graph_test.cpp
    render/creature/shadow_batch_test.cpp
    render/creature/render_request_test.cpp
    render/selection_ring_layout_test.cpp
    render/ground_marker_pattern_test.cpp
    render/ground_marker_tessellation_test.cpp
    render/arrow_cloud_render_test.cpp
    render/projectile_relation_test.cpp
    render/orientation_arrow_mesh_test.cpp
    render/unit_torso_orientation_test.cpp
    render/creature/rigged_mesh_asset_test.cpp
    render/creature/snapshot_mesh_asset_test.cpp
    render/creature/snapshot_mesh_cache_test.cpp
    render/creature/static_attachment_bake_test.cpp
    render/creature/per_unit_archetype_test.cpp
    render/creature/riding_clip_test.cpp
    render/creature/baked_attachment_world_position_test.cpp
    render/creature/baked_horse_attachment_world_position_test.cpp
    render/creature/render_request_batch_parity_test.cpp
    render/creature/creature_bone_probe_test.cpp
    render/creature/template_prewarm_regression_test.cpp
    render/software/software_rasterizer_test.cpp
    render/software/software_backend_integration_test.cpp
    render/software/render_backend_factory_test.cpp
    render/profiling/frame_profile_test.cpp
    render/profiling/gl_counter_coverage_test.cpp
    test_main.cpp
)
target_link_libraries(
    render_tests
    PRIVATE
        GTest::gtest
        GTest::gmock
        Qt${QT_VERSION_MAJOR}::Core
        Qt${QT_VERSION_MAJOR}::Gui
        Qt${QT_VERSION_MAJOR}::Widgets
        engine_core
        render_gl
        creature_bake
        game_sim
)
set_target_properties(render_tests PROPERTIES AUTORCC ON)
soi_register_test_binary(render_tests)
if(TARGET bake_creature_assets)
    add_dependencies(render_tests bake_creature_assets)
endif()
