#pragma once

namespace MapEditor {

enum class ToolType {
  Select,
  Hill,
  HillRidge,
  HillArc,
  HillElbow,
  HillRing,
  Mountain,
  River,
  Road,
  Bridge,
  PropFirecamp,
  PropTent,
  PropSupplyCart,
  PropWeaponRack,
  PropRuins,
  PropMagicShrine,
  PropDeadTree,
  PropBoulder,
  PropPineTree,
  PropOliveTree,
  PropCypressTree,
  PropPalmTree,
  PropPlant,
  PropIronOre,
  PropAbandonedHome,
  PropStatue,
  TroopArcher,
  TroopSwordsman,
  TroopSpearman,
  TroopHorseSwordsman,
  TroopHorseArcher,
  TroopHorseSpearman,
  TroopHealer,
  TroopCatapult,
  TroopBallista,
  TroopElephant,
  TroopRomanLegionOrganizer,
  TroopRomanVeteranConsul,
  TroopRomanFieldCommander,
  TroopCarthageSpearCommander,
  TroopCarthageBowCommander,
  TroopCarthageSwordCommander,
  TroopSkeletonSwordsman,
  TroopSkeletonArcher,
  TroopGravePriest,
  TroopCivilian,
  TroopBuilder,
  UndeadZone,
  Forest,
  WildlifeSheep,
  WildlifeWolves,
  WildlifeBirds,
  Barracks,
  Village,
  DefenseTower,
  Home,
  Marketplace,
  Temple,
  Farm,
  Wall,
  Gate,
  Eraser
};

} // namespace MapEditor
