#include "tool_catalog.h"

#include <algorithm>
#include <array>

namespace MapEditor {

namespace {

using S = ToolSection;
using P = ToolPlacement;
using T = ToolType;

constexpr auto k_tools = std::to_array<ToolSpec>({
    {T::Select,
     S::Selection,
     P::None,
     "Select",
     nullptr,
     "⬚",
     "",
     "Select placed elements, drag them, or double-click to edit.",
     ""},
    {T::Eraser,
     S::Selection,
     P::Erase,
     "Eraser",
     nullptr,
     "✖",
     "",
     "Remove the element or segment under the cursor.",
     ""},

    {T::Hill,
     S::Terrain,
     P::Terrain,
     "Hill",
     nullptr,
     "▲",
     "hill",
     "Place round or width/depth-based hills.",
     ""},
    {T::Mountain,
     S::Terrain,
     P::Terrain,
     "Mountain",
     nullptr,
     "△",
     "mountain",
     "Place high mountains with editable JSON properties.",
     ""},
    {T::HillRidge,
     S::Terrain,
     P::Terrain,
     "Ridge hill",
     "Ridge",
     "▬",
     "hill",
     "Place a straight ridge hill that forces a fight along its length.",
     ""},
    {T::HillArc,
     S::Terrain,
     P::Terrain,
     "Boomerang hill",
     "Boomerang",
     "◜",
     "hill",
     "Place a boomerang ridge. Tuck one into a corner for a natural keep.",
     ""},
    {T::HillElbow,
     S::Terrain,
     P::Terrain,
     "Elbow hill",
     "Elbow",
     "┗",
     "hill",
     "Place an L-shaped ridge that walls off two approaches at once.",
     ""},
    {T::HillRing,
     S::Terrain,
     P::Terrain,
     "Ring hill",
     "Ring",
     "◎",
     "hill",
     "Place a ring of high ground around a hollow bailey.",
     ""},
    {T::Forest,
     S::Terrain,
     P::Forest,
     "Forest",
     nullptr,
     "♠",
     "",
     "Plant a forest. Its ground is closed to horses, siege and elephants; only "
     "foot troops, builders and civilians can thread it.",
     ""},

    {T::PropFirecamp,
     S::WorldProps,
     P::WorldProp,
     "Fire Camp",
     nullptr,
     "◉",
     "firecamp",
     "Place authored fire camps with editable radius and intensity.",
     ""},
    {T::PropTent,
     S::WorldProps,
     P::WorldProp,
     "Tent",
     nullptr,
     "▴",
     "tent",
     "Place authored tents as explicit world props.",
     ""},
    {T::PropSupplyCart,
     S::WorldProps,
     P::WorldProp,
     "Supply Cart",
     nullptr,
     "▭",
     "supply_cart",
     "Place authored supply carts as explicit world props.",
     ""},
    {T::PropWeaponRack,
     S::WorldProps,
     P::WorldProp,
     "Weapon Rack",
     nullptr,
     "⚔",
     "weapon_rack",
     "Place authored weapon racks as explicit world props.",
     ""},
    {T::PropRuins,
     S::WorldProps,
     P::WorldProp,
     "Ruins",
     nullptr,
     "▩",
     "ruins",
     "Place authored ruins as explicit world props.",
     ""},
    {T::PropMagicShrine,
     S::WorldProps,
     P::WorldProp,
     "Magic Shrine",
     nullptr,
     "✦",
     "magic_shrine",
     "Place authored magic shrines as explicit world props.",
     ""},
    {T::PropDeadTree,
     S::WorldProps,
     P::WorldProp,
     "Dead Tree",
     nullptr,
     "♣",
     "dead_tree",
     "Place authored dead trees as explicit world props.",
     ""},
    {T::PropBoulder,
     S::WorldProps,
     P::WorldProp,
     "Boulder",
     nullptr,
     "●",
     "boulder",
     "Place authored boulders as explicit world props.",
     ""},
    {T::PropPineTree,
     S::WorldProps,
     P::WorldProp,
     "Pine Tree",
     nullptr,
     "♠",
     "pine_tree",
     "Place authored pine trees as explicit world props.",
     ""},
    {T::PropOliveTree,
     S::WorldProps,
     P::WorldProp,
     "Olive Tree",
     nullptr,
     "♣",
     "olive_tree",
     "Place authored olive trees as explicit world props.",
     ""},
    {T::PropCypressTree,
     S::WorldProps,
     P::WorldProp,
     "Cypress Tree",
     nullptr,
     "♠",
     "cypress_tree",
     "Place authored cypress trees as explicit world props.",
     ""},
    {T::PropPalmTree,
     S::WorldProps,
     P::WorldProp,
     "Palm Tree",
     nullptr,
     "❈",
     "palm_tree",
     "Place authored palm trees as explicit world props.",
     ""},
    {T::PropPlant,
     S::WorldProps,
     P::WorldProp,
     "Plant",
     nullptr,
     "❀",
     "plant",
     "Place authored ground plants as explicit world props.",
     ""},
    {T::PropIronOre,
     S::WorldProps,
     P::WorldProp,
     "Iron Ore",
     nullptr,
     "◆",
     "iron_ore",
     "Place authored iron ore deposits as explicit world props.",
     ""},
    {T::PropAbandonedHome,
     S::WorldProps,
     P::WorldProp,
     "Abandoned Home",
     nullptr,
     "⌂",
     "abandoned_home",
     "Place a derelict home that blocks movement as an explicit world prop.",
     ""},
    {T::PropStatue,
     S::WorldProps,
     P::WorldProp,
     "Statue",
     nullptr,
     "♟",
     "statue",
     "Place a commemorative statue that blocks movement as an explicit world prop.",
     ""},
    {T::PropCursedGoldVein,
     S::WorldProps,
     P::WorldProp,
     "Cursed Gold Vein",
     nullptr,
     "⚖",
     "cursed_gold_vein",
     "Place a cursed gold vein: neutral until captured, then it pays gold and "
     "bleeds its owner's nearby troops.",
     ""},

    {T::TroopArcher,
     S::TroopsInfantry,
     P::Troop,
     "Archer",
     nullptr,
     "",
     "archer",
     "Place archer troop spawns.",
     ""},
    {T::TroopSwordsman,
     S::TroopsInfantry,
     P::Troop,
     "Swordsman",
     nullptr,
     "",
     "swordsman",
     "Place swordsman troop spawns.",
     ""},
    {T::TroopSpearman,
     S::TroopsInfantry,
     P::Troop,
     "Spearman",
     nullptr,
     "",
     "spearman",
     "Place spearman troop spawns.",
     ""},
    {T::TroopHealer,
     S::TroopsInfantry,
     P::Troop,
     "Healer",
     nullptr,
     "",
     "healer",
     "Place healer troop spawns.",
     ""},
    {T::TroopCivilian,
     S::TroopsInfantry,
     P::Troop,
     "Civilian",
     nullptr,
     "",
     "civilian",
     "Place civilian spawns.",
     ""},
    {T::TroopBuilder,
     S::TroopsInfantry,
     P::Troop,
     "Builder",
     nullptr,
     "",
     "builder",
     "Place builder spawns.",
     ""},

    {T::TroopHorseSwordsman,
     S::TroopsMounted,
     P::Troop,
     "Horse Swordsman",
     nullptr,
     "",
     "horse_swordsman",
     "Place mounted swordsman troop spawns.",
     ""},
    {T::TroopHorseArcher,
     S::TroopsMounted,
     P::Troop,
     "Horse Archer",
     nullptr,
     "",
     "horse_archer",
     "Place mounted archer troop spawns.",
     ""},
    {T::TroopHorseSpearman,
     S::TroopsMounted,
     P::Troop,
     "Horse Spearman",
     nullptr,
     "",
     "horse_spearman",
     "Place mounted spearman troop spawns.",
     ""},
    {T::TroopElephant,
     S::TroopsMounted,
     P::Troop,
     "Elephant",
     nullptr,
     "",
     "elephant",
     "Place elephant troop spawns.",
     ""},
    {T::TroopCatapult,
     S::TroopsMounted,
     P::Troop,
     "Catapult",
     nullptr,
     "",
     "catapult",
     "Place catapult troop spawns.",
     ""},
    {T::TroopBallista,
     S::TroopsMounted,
     P::Troop,
     "Ballista",
     nullptr,
     "",
     "ballista",
     "Place ballista troop spawns.",
     ""},

    {T::TroopRomanLegionOrganizer,
     S::TroopsCommand,
     P::Troop,
     "Fabius Maximus",
     nullptr,
     "",
     "roman_legion_organizer",
     "Place Quintus Fabius Maximus (Roman legion organizer) spawns.",
     ""},
    {T::TroopRomanVeteranConsul,
     S::TroopsCommand,
     P::Troop,
     "Scipio Africanus",
     nullptr,
     "",
     "roman_veteran_consul",
     "Place Publius Cornelius Scipio (Roman veteran consul) spawns.",
     ""},
    {T::TroopRomanFieldCommander,
     S::TroopsCommand,
     P::Troop,
     "Marcellus",
     nullptr,
     "",
     "roman_field_commander",
     "Place Marcus Claudius Marcellus (Roman field commander) spawns.",
     ""},
    {T::TroopCarthageSpearCommander,
     S::TroopsCommand,
     P::Troop,
     "Hanno the Great",
     nullptr,
     "",
     "carthage_spear_commander",
     "Place Hanno the Great (Carthaginian spear commander) spawns.",
     ""},
    {T::TroopCarthageBowCommander,
     S::TroopsCommand,
     P::Troop,
     "Hasdrubal Barca",
     nullptr,
     "",
     "carthage_bow_commander",
     "Place Hasdrubal Barca (Carthaginian bow commander) spawns.",
     ""},
    {T::TroopCarthageSwordCommander,
     S::TroopsCommand,
     P::Troop,
     "Hannibal Barca",
     nullptr,
     "",
     "carthage_sword_commander",
     "Place Hannibal Barca (Carthaginian sword commander) spawns.",
     ""},

    {T::TroopSkeletonSwordsman,
     S::Sepulcher,
     P::Troop,
     "Skeleton Swordsman",
     nullptr,
     "",
     "skeleton_swordsman",
     "Place Iron Sepulcher skeleton swordsman spawns.",
     ""},
    {T::TroopSkeletonArcher,
     S::Sepulcher,
     P::Troop,
     "Skeleton Archer",
     nullptr,
     "",
     "skeleton_archer",
     "Place Iron Sepulcher skeleton archer spawns.",
     ""},
    {T::TroopGravePriest,
     S::Sepulcher,
     P::Troop,
     "Grave Priest",
     nullptr,
     "",
     "grave_priest",
     "Place Iron Sepulcher grave priest spawns.",
     ""},
    {T::UndeadZone,
     S::Sepulcher,
     P::UndeadZone,
     "Undead Zone",
     nullptr,
     "☠",
     "",
     "Place an undead zone (shrine or ruins anchor with skeleton wave spawns). "
     "Double-click to edit waves.",
     ""},

    {T::WildlifeSheep,
     S::Wildlife,
     P::Wildlife,
     "Sheep pasture",
     "Sheep",
     "S",
     "sheep",
     "Mark a sheep pasture. Herds spawn inside the circle and graze within it.",
     ""},
    {T::WildlifeWolves,
     S::Wildlife,
     P::Wildlife,
     "Wolf range",
     "Wolves",
     "W",
     "wolves",
     "Mark a wolf range. Packs den inside the circle and hunt out from it.",
     ""},
    {T::WildlifeBirds,
     S::Wildlife,
     P::Wildlife,
     "Bird roost",
     "Birds",
     "∧",
     "birds",
     "Mark a bird roost. Only used when a map turns flyovers off and keeps the "
     "flock resident.",
     ""},

    {T::River,
     S::Paths,
     P::Linear,
     "River",
     nullptr,
     "〰",
     "river",
     "Click a start point, then click an end point to draw a river.",
     "click start, then end"},
    {T::Road,
     S::Paths,
     P::Linear,
     "Road",
     nullptr,
     "═",
     "road",
     "Draw roads and keep waypoint-based roads editable.",
     "click start, then end"},
    {T::Bridge,
     S::Paths,
     P::Linear,
     "Bridge",
     nullptr,
     "═",
     "bridge",
     "Add bridges across rivers or other crossings.",
     "click start, then end"},
    {T::Ford,
     S::Paths,
     P::Linear,
     "Ford",
     nullptr,
     "≈",
     "ford",
     "Mark a shallow stretch of river that troops can wade: draw it bank to bank "
     "like a bridge; its width is how far the ford runs along the river.",
     "click one bank, then the other"},

    {T::Wall,
     S::Fortifications,
     P::Linear,
     "Wall",
     nullptr,
     "▬",
     "wall",
     "Draw a wall run between two points. Runs snap to the 2-cell wall lattice and "
     "stay axis aligned, and they break around any gate they cross.",
     "click start, then end"},
    {T::Gate,
     S::Fortifications,
     P::Gate,
     "Gate",
     nullptr,
     "┐┌",
     "wall_gate",
     "Set a gate into a wall. Click on a run and the gate takes its axis, snaps to "
     "the lattice and opens a 6-cell gap in it. Click off a run to place a "
     "free-standing gate.",
     "click a wall run, or off it to place free-standing"},

    {T::Barracks,
     S::Structures,
     P::Structure,
     "Barracks",
     nullptr,
     "⌂",
     "barracks",
     "Place barracks and assign them to a player.",
     ""},
    {T::Village,
     S::Structures,
     P::Structure,
     "Village",
     nullptr,
     "⌂",
     "village",
     "Place villages and assign them to a player.",
     ""},
    {T::DefenseTower,
     S::Structures,
     P::Structure,
     "Defense Tower",
     "Tower",
     "♜",
     "defense_tower",
     "Place a defense tower and assign it to a player.",
     ""},
    {T::Home,
     S::Structures,
     P::Structure,
     "Home",
     nullptr,
     "⌂",
     "home",
     "Place a home building and assign it to a player.",
     ""},
    {T::Marketplace,
     S::Structures,
     P::Structure,
     "Marketplace",
     nullptr,
     "◇",
     "marketplace",
     "Place a marketplace building and assign it to a player.",
     ""},
    {T::Temple,
     S::Structures,
     P::Structure,
     "Temple",
     nullptr,
     "△",
     "temple",
     "Place a temple building and assign it to a player.",
     ""},
    {T::Farm,
     S::Structures,
     P::Structure,
     "Farm",
     nullptr,
     "☘",
     "farm",
     "Place a farm and assign it to a player.",
     ""},
});

constexpr auto k_sections = std::to_array<ToolSection>({
    S::Selection,
    S::Terrain,
    S::WorldProps,
    S::TroopsInfantry,
    S::TroopsMounted,
    S::TroopsCommand,
    S::Sepulcher,
    S::Wildlife,
    S::Paths,
    S::Fortifications,
    S::Structures,
});

} // namespace

auto tool_catalog() -> std::span<const ToolSpec> {
  return k_tools;
}

auto tool_spec(ToolType tool) -> const ToolSpec& {
  const auto* found =
      std::find_if(k_tools.begin(), k_tools.end(), [tool](const auto& spec) {
        return spec.tool == tool;
      });
  return found != k_tools.end() ? *found : k_tools.front();
}

auto tools_in_section(ToolSection section) -> QVector<const ToolSpec*> {
  QVector<const ToolSpec*> specs;
  for (const auto& spec : k_tools) {
    if (spec.section == section) {
      specs.append(&spec);
    }
  }
  return specs;
}

auto tool_sections() -> std::span<const ToolSection> {
  return k_sections;
}

auto section_title(ToolSection section) -> QString {
  switch (section) {
  case S::Selection:
    return QStringLiteral("Selection & Cleanup");
  case S::Terrain:
    return QStringLiteral("Terrain");
  case S::WorldProps:
    return QStringLiteral("World Props");
  case S::TroopsInfantry:
    return QStringLiteral("Troops: Infantry & Support");
  case S::TroopsMounted:
    return QStringLiteral("Troops: Mounted & Siege");
  case S::TroopsCommand:
    return QStringLiteral("Troops: Command");
  case S::Sepulcher:
    return QStringLiteral("Troops: Iron Sepulcher");
  case S::Wildlife:
    return QStringLiteral("Wildlife");
  case S::Paths:
    return QStringLiteral("Paths & Bridges");
  case S::Fortifications:
    return QStringLiteral("Walls & Gates");
  case S::Structures:
    return QStringLiteral("Structures");
  }
  return {};
}

auto section_columns(ToolSection section) -> int {
  return section == S::Wildlife ? 3 : 2;
}

auto tool_name(ToolType tool) -> QString {
  return QString::fromUtf8(tool_spec(tool).name);
}

auto tool_card_label(ToolType tool) -> QString {
  const ToolSpec& spec = tool_spec(tool);
  return QString::fromUtf8(spec.card_label != nullptr ? spec.card_label : spec.name);
}

auto tool_description(ToolType tool) -> QString {
  return QString::fromUtf8(tool_spec(tool).description);
}

auto tool_status_label(ToolType tool) -> QString {
  const ToolSpec& spec = tool_spec(tool);
  const QString name = QString::fromUtf8(spec.name);
  const QString hint = QString::fromUtf8(spec.usage_hint);
  return hint.isEmpty() ? name : QStringLiteral("%1 (%2)").arg(name, hint);
}

auto tool_placement(ToolType tool) -> ToolPlacement {
  return tool_spec(tool).placement;
}

auto element_type_for_tool(ToolType tool) -> QString {
  return QString::fromLatin1(tool_spec(tool).element_type);
}

auto tool_matches_filter(const ToolSpec& spec, const QString& filter) -> bool {
  const QString needle = filter.trimmed();
  if (needle.isEmpty()) {
    return true;
  }
  const auto contains = [&needle](const char* text) {
    return text != nullptr &&
           QString::fromUtf8(text).contains(needle, Qt::CaseInsensitive);
  };
  return contains(spec.name) || contains(spec.card_label) ||
         contains(spec.element_type) ||
         section_title(spec.section).contains(needle, Qt::CaseInsensitive);
}

} // namespace MapEditor
