

#pragma once

#include "../rig_def.h"

namespace Render::RigDSL::Barracks {

enum Anchor : AnchorId {

  Platform_BaseLow,
  Platform_BaseHigh,
  Platform_TopLow,
  Platform_TopHigh,

  Court_StoneLow,
  Court_StoneHigh,
  Court_PoolLow,
  Court_PoolHigh,
  Court_PoolTrimSLow,
  Court_PoolTrimSHigh,
  Court_PoolTrimNLow,
  Court_PoolTrimNHigh,

  Court_PillarBot,
  Court_PillarTop,
  Court_PillarCapLow,
  Court_PillarCapHigh,

  Wall_BackLow,
  Wall_BackHigh,
  Wall_LeftLow,
  Wall_LeftHigh,
  Wall_RightLow,
  Wall_RightHigh,

  Door_LDoorLow,
  Door_LDoorHigh,
  Door_LLintelLow,
  Door_LLintelHigh,
  Door_RDoorLow,
  Door_RDoorHigh,
  Door_RLintelLow,
  Door_RLintelHigh,

  Goods_Amp1Bot,
  Goods_Amp1Top,
  Goods_Amp2Bot,
  Goods_Amp2Top,
  Goods_Amp3Bot,
  Goods_Amp3Top,
};

namespace C {
inline constexpr PackedColor k_limestone{245, 239, 224, 255};
inline constexpr PackedColor k_limestone_shade{224, 217, 199, 255};
inline constexpr PackedColor k_limestone_dark{204, 194, 178, 255};
inline constexpr PackedColor k_marble{250, 247, 242, 255};
inline constexpr PackedColor k_cedar_dark{97, 66, 41, 255};
inline constexpr PackedColor k_terracotta{209, 158, 115, 255};
inline constexpr PackedColor k_terracotta_dark{173, 122, 82, 255};
inline constexpr PackedColor k_blue_accent{71, 122, 173, 255};
inline constexpr PackedColor k_blue_light{102, 153, 204, 255};
} // namespace C

inline constexpr PartDef k_parts[] = {

    {PartKind::Box,
     0,
     0xFFU,
     PaletteSlot::Literal,
     C::k_limestone_dark,
     Platform_BaseLow,
     Platform_BaseHigh,
     k_invalid_scalar,
     1.0F,
     1.0F,
     1.0F,
     1.0F,
     1.0F},
    {PartKind::Box,
     0,
     0xFFU,
     PaletteSlot::Literal,
     C::k_limestone,
     Platform_TopLow,
     Platform_TopHigh,
     k_invalid_scalar,
     1.0F,
     1.0F,
     1.0F,
     1.0F,
     1.0F},

    {PartKind::Box,
     0,
     0xFFU,
     PaletteSlot::Literal,
     C::k_limestone_shade,
     Court_StoneLow,
     Court_StoneHigh,
     k_invalid_scalar,
     1.0F,
     1.0F,
     1.0F,
     1.0F,
     1.0F},
    {PartKind::Box,
     0,
     0xFFU,
     PaletteSlot::Literal,
     C::k_blue_light,
     Court_PoolLow,
     Court_PoolHigh,
     k_invalid_scalar,
     1.0F,
     1.0F,
     1.0F,
     1.0F,
     1.0F},
    {PartKind::Box,
     0,
     0xFFU,
     PaletteSlot::Literal,
     C::k_blue_accent,
     Court_PoolTrimSLow,
     Court_PoolTrimSHigh,
     k_invalid_scalar,
     1.0F,
     1.0F,
     1.0F,
     1.0F,
     1.0F},
    {PartKind::Box,
     0,
     0xFFU,
     PaletteSlot::Literal,
     C::k_blue_accent,
     Court_PoolTrimNLow,
     Court_PoolTrimNHigh,
     k_invalid_scalar,
     1.0F,
     1.0F,
     1.0F,
     1.0F,
     1.0F},
    {PartKind::Cylinder,
     0,
     0xFFU,
     PaletteSlot::Literal,
     C::k_marble,
     Court_PillarBot,
     Court_PillarTop,
     k_invalid_scalar,
     0.06F,
     1.0F,
     1.0F,
     1.0F,
     1.0F},
    {PartKind::Box,
     0,
     0xFFU,
     PaletteSlot::Literal,
     C::k_blue_accent,
     Court_PillarCapLow,
     Court_PillarCapHigh,
     k_invalid_scalar,
     1.0F,
     1.0F,
     1.0F,
     1.0F,
     1.0F},

    {PartKind::Box,
     0,
     0xFFU,
     PaletteSlot::Literal,
     C::k_limestone,
     Wall_BackLow,
     Wall_BackHigh,
     k_invalid_scalar,
     1.0F,
     1.0F,
     1.0F,
     1.0F,
     1.0F},
    {PartKind::Box,
     0,
     0xFFU,
     PaletteSlot::Literal,
     C::k_limestone,
     Wall_LeftLow,
     Wall_LeftHigh,
     k_invalid_scalar,
     1.0F,
     1.0F,
     1.0F,
     1.0F,
     1.0F},
    {PartKind::Box,
     0,
     0xFFU,
     PaletteSlot::Literal,
     C::k_limestone,
     Wall_RightLow,
     Wall_RightHigh,
     k_invalid_scalar,
     1.0F,
     1.0F,
     1.0F,
     1.0F,
     1.0F},

    {PartKind::Box,
     0,
     0xFFU,
     PaletteSlot::Literal,
     C::k_cedar_dark,
     Door_LDoorLow,
     Door_LDoorHigh,
     k_invalid_scalar,
     1.0F,
     1.0F,
     1.0F,
     1.0F,
     1.0F},
    {PartKind::Box,
     0,
     0xFFU,
     PaletteSlot::Literal,
     C::k_blue_accent,
     Door_LLintelLow,
     Door_LLintelHigh,
     k_invalid_scalar,
     1.0F,
     1.0F,
     1.0F,
     1.0F,
     1.0F},
    {PartKind::Box,
     0,
     0xFFU,
     PaletteSlot::Literal,
     C::k_cedar_dark,
     Door_RDoorLow,
     Door_RDoorHigh,
     k_invalid_scalar,
     1.0F,
     1.0F,
     1.0F,
     1.0F,
     1.0F},
    {PartKind::Box,
     0,
     0xFFU,
     PaletteSlot::Literal,
     C::k_blue_accent,
     Door_RLintelLow,
     Door_RLintelHigh,
     k_invalid_scalar,
     1.0F,
     1.0F,
     1.0F,
     1.0F,
     1.0F},

    {PartKind::Cylinder,
     0,
     0xFFU,
     PaletteSlot::Literal,
     C::k_terracotta_dark,
     Goods_Amp1Bot,
     Goods_Amp1Top,
     k_invalid_scalar,
     0.08F,
     1.0F,
     1.0F,
     1.0F,
     1.0F},
    {PartKind::Cylinder,
     0,
     0xFFU,
     PaletteSlot::Literal,
     C::k_terracotta,
     Goods_Amp2Bot,
     Goods_Amp2Top,
     k_invalid_scalar,
     0.07F,
     1.0F,
     1.0F,
     1.0F,
     1.0F},
    {PartKind::Cylinder,
     0,
     0xFFU,
     PaletteSlot::Literal,
     C::k_blue_accent,
     Goods_Amp3Bot,
     Goods_Amp3Top,
     k_invalid_scalar,
     0.06F,
     1.0F,
     1.0F,
     1.0F,
     1.0F},
};

inline constexpr RigDef k_rig = make_rig("barracks_roman_structure", k_parts);

} // namespace Render::RigDSL::Barracks
