#pragma once

#include "../rig_def.h"

namespace Render::RigDSL::RomanLightHelmet {

enum Anchor : AnchorId {
  Helmet_Top,
  Helmet_Bot,
  Apex,
  Ring_Low_Top,
  Ring_Low_Bot,
  Ring_High_Top,
  Ring_High_Bot,
  Neck_Guard_Top,
  Neck_Guard_Bot,
  Crest_Base,
  Crest_Mid,
  Crest_Top,
};

enum Scalar : ScalarId {
  S_Helmet_R,
  S_Helmet_R_Apex,
  S_Helmet_R_Ring_Low,
  S_Helmet_R_Ring_Hi,
  S_Helmet_R_Neck,
};

inline constexpr PartDef kParts[] = {

    {PartKind::Cylinder,
     2,
     0xFFU,
     PaletteSlot::Metal,
     {},
     Helmet_Bot,
     Helmet_Top,
     S_Helmet_R,
     1.0F,
     1.0F,
     1.0F,
     1.0F,
     1.0F},

    {PartKind::Cone,
     2,
     0xFFU,
     PaletteSlot::Metal_Accent,
     {},
     Helmet_Top,
     Apex,
     S_Helmet_R_Apex,
     1.0F,
     1.0F,
     1.0F,
     1.0F,
     1.0F},

    {PartKind::Cylinder,
     2,
     0xFFU,
     PaletteSlot::Metal_Accent,
     {},
     Ring_Low_Bot,
     Ring_Low_Top,
     S_Helmet_R_Ring_Low,
     1.0F,
     1.0F,
     1.0F,
     1.0F,
     1.0F},

    {PartKind::Cylinder,
     2,
     0xFFU,
     PaletteSlot::Metal,
     {},
     Ring_High_Bot,
     Ring_High_Top,
     S_Helmet_R_Ring_Hi,
     1.0F,
     1.0F,
     1.0F,
     1.0F,
     1.04F},

    {PartKind::Cylinder,
     2,
     0xFFU,
     PaletteSlot::Metal,
     {},
     Neck_Guard_Bot,
     Neck_Guard_Top,
     S_Helmet_R_Neck,
     1.0F,
     1.0F,
     1.0F,
     1.0F,
     0.90F},

    {PartKind::Cylinder,
     2,
     0xFFU,
     PaletteSlot::Metal_Accent,
     {},
     Crest_Base,
     Crest_Mid,
     kInvalidScalar,
     0.018F,
     1.0F,
     1.0F,
     1.0F,
     1.0F},

    {PartKind::Cone,
     0,
     0xFFU,
     PaletteSlot::Literal,
     {224, 46, 46, 255},
     Crest_Mid,
     Crest_Top,
     kInvalidScalar,
     0.042F,
     1.0F,
     1.0F,
     1.0F,
     1.0F},

    {PartKind::Sphere,
     2,
     0xFFU,
     PaletteSlot::Metal_Accent,
     {},
     Crest_Top,
     kInvalidAnchor,
     kInvalidScalar,
     0.020F,
     1.0F,
     1.0F,
     1.0F,
     1.0F},
};

inline constexpr RigDef kRig = make_rig("roman_light_helmet", kParts);

} // namespace Render::RigDSL::RomanLightHelmet
