# Entity/nation renderers (Phase 2 owner). Edit ONLY this file for render/entity/* sources.
set(RENDER_ENTITY_SOURCES
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/registry.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/archer_renderer_common.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/nations/roman/archer_renderer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/nations/carthage/archer_renderer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/nations/roman/archer_style.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/nations/carthage/archer_style.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/swordsman_renderer_common.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/nations/roman/swordsman_renderer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/nations/carthage/swordsman_renderer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/nations/roman/swordsman_style.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/nations/carthage/swordsman_style.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/nations/roman/spearman_renderer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/nations/carthage/spearman_renderer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/nations/roman/spearman_style.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/nations/carthage/spearman_style.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/nations/equipment_loadout_catalog.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/horse_renderer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/mounted_humanoid_renderer_base.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/mounted_prepare.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/mounted_knight_renderer_base.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/horse_archer_renderer_base.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/horse_spearman_renderer_base.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/nations/roman/horse_swordsman_renderer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/nations/carthage/horse_swordsman_renderer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/nations/roman/horse_archer_renderer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/nations/carthage/horse_archer_renderer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/nations/roman/horse_spearman_renderer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/nations/carthage/horse_spearman_renderer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/nations/roman/healer_renderer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/nations/roman/healer_style.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/nations/carthage/healer_renderer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/nations/carthage/healer_style.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/nations/roman/builder_renderer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/nations/roman/builder_style.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/nations/carthage/builder_renderer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/nations/carthage/builder_style.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/healing_beam_renderer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/healing_waves_renderer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/healer_aura_renderer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/commander_aura_renderer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/combat_dust_renderer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/building_archetype_desc.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/building_render_common.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/wall_renderer_common.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/barracks_renderer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/nations/roman/barracks_renderer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/nations/carthage/barracks_renderer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/defense_tower_renderer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/nations/roman/defense_tower_renderer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/nations/carthage/defense_tower_renderer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/home_renderer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/nations/roman/home_renderer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/nations/carthage/home_renderer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/marketplace_renderer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/nations/roman/marketplace_renderer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/nations/carthage/marketplace_renderer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/wall_renderer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/nations/roman/wall_renderer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/nations/carthage/wall_renderer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/catapult_renderer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/nations/roman/catapult_renderer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/nations/carthage/catapult_renderer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/ballista_renderer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/nations/roman/ballista_renderer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/nations/carthage/ballista_renderer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/elephant_renderer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/nations/carthage/elephant_renderer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/home_renderer_common.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/marketplace_renderer_common.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/defense_tower_renderer_common.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/barracks_renderer_common.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/catapult_renderer_common.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/ballista_renderer_common.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/spearman_renderer_common.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/healer_renderer_common.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/entity/builder_renderer_common.cpp
)
