# Creature/animation pipeline sources (humanoid, creature, horse, elephant).
set(RENDER_CREATURE_SOURCES
    ${CMAKE_CURRENT_SOURCE_DIR}/horse/horse_profile_data.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/horse/prepare.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/horse/horse_spec.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/horse/horse_motion.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/horse/horse_manifest.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/elephant/elephant_profile_data.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/elephant/elephant_motion.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/elephant/prepare.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/elephant/elephant_spec.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/elephant/elephant_manifest.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/humanoid/humanoid_math.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/humanoid/rig.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/humanoid/prepare.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/humanoid/prepare_animation.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/humanoid/prepare_state.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/humanoid/prepare_submission.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/humanoid/poser.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/humanoid/facial_hair_catalog.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/humanoid/formation_calculator.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/humanoid/style_palette.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/humanoid/pose_controller.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/humanoid/mounted_pose_controller.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/humanoid/pose_primitives.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/humanoid/skeleton.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/humanoid/humanoid_full_builder.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/humanoid/humanoid_spec.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/creature/bpat/bpat_writer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/creature/bpat/bpat_reader.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/creature/bpat/bpat_registry.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/creature/snapshot_mesh_asset.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/creature/snapshot_mesh_registry.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/creature/skeleton.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/creature/part_graph.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/creature/spec.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/creature/combat_visual_state.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/creature/species_manifest.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/creature/runtime_bake_guard.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/creature/quadruped/skeleton_factory.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/creature/quadruped/gait.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/creature/quadruped/mesh_graph.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/creature/anatomy_bake.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/creature/archetype_registry.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/creature/pose_intent.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/creature/pipeline/creature_render_state.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/creature/pipeline/creature_pipeline.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/creature/pipeline/creature_visual_definition.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/creature/pipeline/creature_asset.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/creature/pipeline/prepared_submit.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/creature/pipeline/shadow_batch.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/creature/pipeline/creature_prepared_state.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/creature/pipeline/lod_decision.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/creature/pipeline/bpat_playback.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/creature/pipeline/preparation_common.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/creature/pipeline/humanoid_animation_selection.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/creature/pipeline/creature_render_graph.cpp
)
