

#ifndef SOI_QUALITY_TIER
#define SOI_QUALITY_TIER 2
#endif

#define SOI_TIER_LOW 0
#define SOI_TIER_MEDIUM 1
#define SOI_TIER_HIGH 2
#define SOI_TIER_ULTRA 3

#if SOI_QUALITY_TIER >= SOI_TIER_ULTRA
#define SOI_TERRAIN_NOISE_OCTAVES 6
#define SOI_DETAIL_OCTAVES 3
#elif SOI_QUALITY_TIER >= SOI_TIER_HIGH
#define SOI_TERRAIN_NOISE_OCTAVES 5
#define SOI_DETAIL_OCTAVES 3
#elif SOI_QUALITY_TIER >= SOI_TIER_MEDIUM
#define SOI_TERRAIN_NOISE_OCTAVES 3
#define SOI_DETAIL_OCTAVES 2
#else
#define SOI_TERRAIN_NOISE_OCTAVES 2
#define SOI_DETAIL_OCTAVES 1
#endif

#if SOI_QUALITY_TIER >= SOI_TIER_MEDIUM
#define SOI_SURFACE_DETAIL 1
#else
#define SOI_SURFACE_DETAIL 0
#endif

#if SOI_QUALITY_TIER >= SOI_TIER_ULTRA
#define SOI_ULTRA_EFFECTS 1
#else
#define SOI_ULTRA_EFFECTS 0
#endif
